#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK_ROOT="${DROPSHELF_COMPRESSION_WORK_DIR:-${TMPDIR:-/tmp}/dropshelf-compression-tools}"
DOWNLOAD_DIR="$WORK_ROOT/downloads"
SOURCE_DIR="$WORK_ROOT/sources"
BUILD_DIR="$WORK_ROOT/build"
PREFIX_DIR="$WORK_ROOT/prefix"
EMPTY_PKGCONFIG="$WORK_ROOT/empty-pkgconfig"
TOOLS_DIR="$ROOT/Resources/CompressionTools"
BIN_DIR="$TOOLS_DIR/bin"
LICENSE_DIR="$TOOLS_DIR/licenses"
SDK_PATH="$(xcrun --sdk macosx --show-sdk-path)"

QPDF_VERSION=12.4.2
QPDF_SHA256=8a58af5b6141319287c1883bec8bd1bd545b7567b7fc5e6ce5d25a1c85f36397
QPDF_CHECKSUM_SHA256=bb4472ec2efb3fe4c4a49f030906c734506ffd99cb27abab0eb2f15ab1820d69
JPEG_VERSION=3.2.0
JPEG_SHA256=6f30092cef9fb839779646608f4ee14ae3cbac989c47fa05e841b0841f09878e
ZOPFLI_VERSION=1.0.3
ZOPFLI_COMMIT=bd64b2f0553d4f1ef4e6627647c5d9fc8c71ffc0
ZOPFLI_SHA256=e955a7739f71af37ef3349c4fa141c648e8775bceb2195be07e86f8e638814bd
OXIPNG_VERSION=10.2.1
OXIPNG_SHA256=7039fcfc78e8aa1ed2b57d848057a0296f082e92b3e1807ac65402d10d926764

mkdir -p "$DOWNLOAD_DIR" "$EMPTY_PKGCONFIG"

fetch() {
    local url="$1"
    local output="$2"
    local expected="$3"
    if [[ ! -f "$output" ]]; then
        curl -fL --retry 3 --output "$output" "$url"
    fi
    local actual
    actual="$(shasum -a 256 "$output" | awk '{print $1}')"
    if [[ "$actual" != "$expected" ]]; then
        echo "Checksum mismatch for $output" >&2
        exit 1
    fi
}

fetch \
  "https://github.com/qpdf/qpdf/releases/download/v${QPDF_VERSION}/qpdf-${QPDF_VERSION}.tar.gz" \
  "$DOWNLOAD_DIR/qpdf-${QPDF_VERSION}.tar.gz" "$QPDF_SHA256"
fetch \
  "https://github.com/qpdf/qpdf/releases/download/v${QPDF_VERSION}/qpdf-${QPDF_VERSION}.sha256" \
  "$DOWNLOAD_DIR/qpdf-${QPDF_VERSION}.sha256" "$QPDF_CHECKSUM_SHA256"
if ! grep -F "${QPDF_SHA256}  qpdf-${QPDF_VERSION}.tar.gz" \
  "$DOWNLOAD_DIR/qpdf-${QPDF_VERSION}.sha256" >/dev/null; then
    echo "The official qpdf checksum manifest does not match the pinned source." >&2
    exit 1
fi
fetch \
  "https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/${JPEG_VERSION}/libjpeg-turbo-${JPEG_VERSION}.tar.gz" \
  "$DOWNLOAD_DIR/libjpeg-turbo-${JPEG_VERSION}.tar.gz" "$JPEG_SHA256"
fetch \
  "https://github.com/google/zopfli/archive/refs/tags/zopfli-${ZOPFLI_VERSION}.tar.gz" \
  "$DOWNLOAD_DIR/zopfli-${ZOPFLI_VERSION}.tar.gz" "$ZOPFLI_SHA256"
fetch \
  "https://github.com/oxipng/oxipng/releases/download/v${OXIPNG_VERSION}/oxipng-${OXIPNG_VERSION}-aarch64-apple-darwin.tar.gz" \
  "$DOWNLOAD_DIR/oxipng-${OXIPNG_VERSION}-aarch64-apple-darwin.tar.gz" "$OXIPNG_SHA256"

rm -rf "$SOURCE_DIR" "$BUILD_DIR" "$PREFIX_DIR"
mkdir -p "$SOURCE_DIR" "$BUILD_DIR" "$PREFIX_DIR" "$BIN_DIR" "$LICENSE_DIR"
tar -xzf "$DOWNLOAD_DIR/qpdf-${QPDF_VERSION}.tar.gz" -C "$SOURCE_DIR"
tar -xzf "$DOWNLOAD_DIR/libjpeg-turbo-${JPEG_VERSION}.tar.gz" -C "$SOURCE_DIR"
tar -xzf "$DOWNLOAD_DIR/zopfli-${ZOPFLI_VERSION}.tar.gz" -C "$SOURCE_DIR"
tar -xzf "$DOWNLOAD_DIR/oxipng-${OXIPNG_VERSION}-aarch64-apple-darwin.tar.gz" -C "$SOURCE_DIR"

# Remove non-license generator-attribution comments from vendored shell
# completion text. This preserves all completion logic, copyrights and license
# notices while keeping internal tooling labels out of the shipped binary.
while IFS= read -r completion_file; do
    sed -i '' '/Most of this logic was generated by /d' "$completion_file"
done < <(grep -rl 'Most of this logic was generated by ' "$SOURCE_DIR/qpdf-${QPDF_VERSION}")

export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-0}"
MAP_FLAGS="-ffile-prefix-map=${WORK_ROOT}=. -ffile-prefix-map=${ROOT}=. -fdebug-prefix-map=${WORK_ROOT}=. -fdebug-prefix-map=${ROOT}=."

cmake -S "$SOURCE_DIR/zopfli-zopfli-${ZOPFLI_VERSION}" -B "$BUILD_DIR/zopfli" \
  -DCMAKE_BUILD_TYPE=MinSizeRel \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0 \
  -DCMAKE_OSX_ARCHITECTURES=arm64 \
  -DCMAKE_INSTALL_PREFIX="$PREFIX_DIR/zopfli" \
  -DBUILD_SHARED_LIBS=OFF \
  -DZOPFLI_BUILD_SHARED=OFF \
  -DZOPFLI_BUILD_INSTALL=ON \
  "-DCMAKE_C_FLAGS=$MAP_FLAGS" \
  "-DCMAKE_CXX_FLAGS=$MAP_FLAGS"
cmake --build "$BUILD_DIR/zopfli" --config MinSizeRel --parallel
cmake --install "$BUILD_DIR/zopfli" --config MinSizeRel

cmake -S "$SOURCE_DIR/libjpeg-turbo-${JPEG_VERSION}" -B "$BUILD_DIR/jpeg" \
  -DCMAKE_BUILD_TYPE=MinSizeRel \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0 \
  -DCMAKE_OSX_ARCHITECTURES=arm64 \
  -DCMAKE_INSTALL_PREFIX="$PREFIX_DIR/jpeg" \
  -DENABLE_SHARED=OFF \
  -DENABLE_STATIC=ON \
  -DWITH_TURBOJPEG=OFF \
  -DWITH_TOOLS=ON \
  -DWITH_TESTS=ON \
  -DWITH_SIMD=ON \
  "-DCMAKE_C_FLAGS=$MAP_FLAGS"
cmake --build "$BUILD_DIR/jpeg" --config MinSizeRel --parallel
ctest --test-dir "$BUILD_DIR/jpeg" --build-config MinSizeRel --output-on-failure
cmake --install "$BUILD_DIR/jpeg" --config MinSizeRel

PKG_CONFIG_LIBDIR="$EMPTY_PKGCONFIG" PKG_CONFIG_PATH= cmake \
  -S "$SOURCE_DIR/qpdf-${QPDF_VERSION}" -B "$BUILD_DIR/qpdf" \
  -DCMAKE_BUILD_TYPE=MinSizeRel \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0 \
  -DCMAKE_OSX_ARCHITECTURES=arm64 \
  -DCMAKE_OSX_SYSROOT="$SDK_PATH" \
  -DCMAKE_INSTALL_PREFIX="$PREFIX_DIR/qpdf" \
  -DBUILD_SHARED_LIBS=OFF \
  -DBUILD_STATIC_LIBS=ON \
  -DBUILD_DOC=OFF \
  -DINSTALL_MANUAL=OFF \
  -DINSTALL_EXAMPLES=OFF \
  -DINSTALL_PKGCONFIG=OFF \
  -DINSTALL_CMAKE_PACKAGE=OFF \
  -DUSE_IMPLICIT_CRYPTO=OFF \
  -DREQUIRE_CRYPTO_NATIVE=ON \
  -DREQUIRE_CRYPTO_OPENSSL=OFF \
  -DREQUIRE_CRYPTO_GNUTLS=OFF \
  -DDEFAULT_CRYPTO=native \
  -DZOPFLI=ON \
  -DSTATIC_JPEG=ON \
  -DZLIB_H_PATH="$SDK_PATH/usr/include" \
  -DZLIB_LIB_PATH="$SDK_PATH/usr/lib/libz.tbd" \
  -DLIBJPEG_H_PATH="$PREFIX_DIR/jpeg/include" \
  -DLIBJPEG_LIB_PATH="$PREFIX_DIR/jpeg/lib/libjpeg.a" \
  -DZOPFLI_H_PATH="$PREFIX_DIR/zopfli/include" \
  -DZOPFLI_LIB_PATH="$PREFIX_DIR/zopfli/lib/libzopfli.a" \
  "-DCMAKE_C_FLAGS=$MAP_FLAGS" \
  "-DCMAKE_CXX_FLAGS=$MAP_FLAGS" \
  "-DCMAKE_EXE_LINKER_FLAGS=-Wl,-dead_strip"
cmake --build "$BUILD_DIR/qpdf" --config MinSizeRel --parallel
ctest --test-dir "$BUILD_DIR/qpdf" --build-config MinSizeRel --output-on-failure
cmake --install "$BUILD_DIR/qpdf" --config MinSizeRel

cp "$PREFIX_DIR/qpdf/bin/qpdf" "$BIN_DIR/qpdf"
cp "$PREFIX_DIR/jpeg/bin/jpegtran" "$BIN_DIR/jpegtran"
cp "$SOURCE_DIR/oxipng-${OXIPNG_VERSION}-aarch64-apple-darwin/oxipng" "$BIN_DIR/oxipng"

CXX_FLAGS=(
  -std=c++17 -Os -DNDEBUG -Wall -Wextra -Werror -arch arm64 -mmacosx-version-min=13.0
  "-ffile-prefix-map=${WORK_ROOT}=." "-ffile-prefix-map=${ROOT}=."
  "-fdebug-prefix-map=${WORK_ROOT}=." "-fdebug-prefix-map=${ROOT}=."
)
xcrun clang++ "${CXX_FLAGS[@]}" \
  -I"$PREFIX_DIR/qpdf/include" \
  "$ROOT/Sources/Compression/PDFVerifier.cpp" \
  "$PREFIX_DIR/qpdf/lib/libqpdf.a" \
  "$PREFIX_DIR/zopfli/lib/libzopfli.a" \
  "$PREFIX_DIR/jpeg/lib/libjpeg.a" \
  -lz -o "$BIN_DIR/pdf-verify"
xcrun clang++ "${CXX_FLAGS[@]}" \
  -I"$PREFIX_DIR/jpeg/include" \
  "$ROOT/Sources/Compression/ImageVerifier.cpp" \
  "$PREFIX_DIR/jpeg/lib/libjpeg.a" \
  -lz -o "$BIN_DIR/image-verify"

for helper in qpdf jpegtran oxipng pdf-verify image-verify; do
    strip -S -x "$BIN_DIR/$helper"
    codesign --force --sign - --options runtime "$BIN_DIR/$helper"
    codesign --verify --strict --verbose=2 "$BIN_DIR/$helper"
    minos="$(otool -l "$BIN_DIR/$helper" | awk '
      /LC_BUILD_VERSION/ { in_build = 1; next }
      in_build && /minos/ { print $2; exit }
    ')"
    major="${minos%%.*}"
    if [[ -z "$minos" || "$major" -gt 13 ]]; then
        echo "$helper requires macOS $minos; expected macOS 13 or earlier" >&2
        exit 1
    fi
    if otool -L "$BIN_DIR/$helper" | tail -n +2 | awk '{print $1}' | \
      grep -Ev '^(/usr/lib/|/System/Library/)' >/dev/null; then
        echo "$helper has a non-system runtime dependency" >&2
        otool -L "$BIN_DIR/$helper" >&2
        exit 1
    fi
    if strings -a "$BIN_DIR/$helper" | \
      grep -E "${WORK_ROOT}|${ROOT}|/Users/|/home/" >/dev/null; then
        echo "$helper contains a private build path" >&2
        exit 1
    fi
done

"$BIN_DIR/qpdf" --version | grep -F "qpdf version ${QPDF_VERSION}" >/dev/null
"$BIN_DIR/qpdf" --show-crypto | grep -Fx native >/dev/null
QPDF_ZOPFLI=force "$BIN_DIR/qpdf" --zopfli | grep -F "zopfli is active" >/dev/null
"$BIN_DIR/jpegtran" -version 2>&1 | grep -F "libjpeg-turbo version ${JPEG_VERSION}" >/dev/null
"$BIN_DIR/oxipng" --version | grep -F "oxipng ${OXIPNG_VERSION}" >/dev/null

cp "$SOURCE_DIR/qpdf-${QPDF_VERSION}/LICENSE.txt" "$LICENSE_DIR/qpdf-LICENSE.txt"
cp "$SOURCE_DIR/libjpeg-turbo-${JPEG_VERSION}/LICENSE.md" "$LICENSE_DIR/libjpeg-turbo-LICENSE.md"
cp "$SOURCE_DIR/zopfli-zopfli-${ZOPFLI_VERSION}/COPYING" "$LICENSE_DIR/zopfli-COPYING"
cp "$SOURCE_DIR/oxipng-${OXIPNG_VERSION}-aarch64-apple-darwin/LICENSE" "$LICENSE_DIR/oxipng-LICENSE"

sha_for() {
    shasum -a 256 "$BIN_DIR/$1" | awk '{print $1}'
}

cat > "$TOOLS_DIR/manifest.json" <<EOF
{
  "schemaVersion": 1,
  "tools": [
    {"name":"qpdf","path":"bin/qpdf","sha256":"$(sha_for qpdf)","version":"${QPDF_VERSION}"},
    {"name":"jpegtran","path":"bin/jpegtran","sha256":"$(sha_for jpegtran)","version":"${JPEG_VERSION}"},
    {"name":"oxipng","path":"bin/oxipng","sha256":"$(sha_for oxipng)","version":"${OXIPNG_VERSION}"},
    {"name":"pdf-verify","path":"bin/pdf-verify","sha256":"$(sha_for pdf-verify)","version":"1.0.0","sourceSha256":"$(shasum -a 256 "$ROOT/Sources/Compression/PDFVerifier.cpp" | awk '{print $1}')"},
    {"name":"image-verify","path":"bin/image-verify","sha256":"$(sha_for image-verify)","version":"1.0.0","sourceSha256":"$(shasum -a 256 "$ROOT/Sources/Compression/ImageVerifier.cpp" | awk '{print $1}')"}
  ]
}
EOF

cat > "$TOOLS_DIR/sources.json" <<EOF
{
  "schemaVersion": 1,
  "target": "arm64-apple-macos13",
  "components": [
    {"name":"qpdf","version":"${QPDF_VERSION}","source":"https://github.com/qpdf/qpdf/releases/download/v${QPDF_VERSION}/qpdf-${QPDF_VERSION}.tar.gz","sha256":"${QPDF_SHA256}","license":"Apache-2.0","sourceAdjustment":"Removed non-license generator-attribution comments from shell completion text."},
    {"name":"libjpeg-turbo","version":"${JPEG_VERSION}","source":"https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/${JPEG_VERSION}/libjpeg-turbo-${JPEG_VERSION}.tar.gz","sha256":"${JPEG_SHA256}","license":"BSD-3-Clause AND IJG AND Zlib"},
    {"name":"zopfli","version":"${ZOPFLI_VERSION}","commit":"${ZOPFLI_COMMIT}","source":"https://github.com/google/zopfli/archive/refs/tags/zopfli-${ZOPFLI_VERSION}.tar.gz","sha256":"${ZOPFLI_SHA256}","license":"Apache-2.0"},
    {"name":"oxipng","version":"${OXIPNG_VERSION}","source":"https://github.com/oxipng/oxipng/releases/download/v${OXIPNG_VERSION}/oxipng-${OXIPNG_VERSION}-aarch64-apple-darwin.tar.gz","sha256":"${OXIPNG_SHA256}","license":"MIT"}
  ]
}
EOF

# GitHub API commits cannot set executable mode on newly added files. Keep the
# tracked helpers as ordinary data files; build.sh makes the copied bundle
# helpers executable before signing and sealing the app.
for helper in qpdf jpegtran oxipng pdf-verify image-verify; do
    chmod 0644 "$BIN_DIR/$helper"
done

echo "Compression tools are ready in $TOOLS_DIR"
