import Cocoa
import Combine

enum ClipboardPasteboard {
    static let privateType = NSPasteboard.PasteboardType("com.dropshelf.clipboard.private")
    static let blockedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "org.nspasteboard.RestoredType",
        "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping",
        "Pasteboard generator type", "com.agilebits.onepassword",
        "com.apple.is-remote-clipboard", privateType.rawValue
    ]
    enum ReadResult {
        case captured(ClipboardPayload), ignored, tooLarge, unstable
    }

    static func read(_ board: NSPasteboard, maximumBytes: Int = 32 * 1024 * 1024) -> ReadResult {
        let version = board.changeCount
        let globalTypes = Set((board.types ?? []).map(\.rawValue))
        guard globalTypes.isDisjoint(with: blockedTypes),
              let sourceItems = board.pasteboardItems, !sourceItems.isEmpty,
              sourceItems.allSatisfy({ Set($0.types.map(\.rawValue)).isDisjoint(with: blockedTypes) }) else { return .ignored }
        var captured: [[String: Data]] = []
        var byteCount = 0
        for item in sourceItems {
            // File copies and promises stay in the established Files workflow.
            guard !item.types.contains(.fileURL), !item.types.contains(NSPasteboard.PasteboardType("NSFilenamesPboardType")),
                  Set(item.types.map(\.rawValue)).isDisjoint(with: Set(NSFilePromiseReceiver.readableDraggedTypes)) else { return .ignored }
            var representations: [String: Data] = [:]
            for type in ClipboardPayload.supportedTypes where item.types.contains(NSPasteboard.PasteboardType(type)) {
                guard let data = item.data(forType: NSPasteboard.PasteboardType(type)) else { return .unstable }
                guard data.count <= maximumBytes - byteCount else { return .tooLarge }
                byteCount += data.count
                representations[type] = data
            }
            guard !representations.isEmpty else { return .ignored }
            captured.append(representations)
        }
        guard board.changeCount == version else { return .unstable }
        guard Set((board.types ?? []).map(\.rawValue)).isDisjoint(with: blockedTypes),
              sourceItems.allSatisfy({ Set($0.types.map(\.rawValue)).isDisjoint(with: blockedTypes) }) else { return .ignored }
        guard let payload = ClipboardPayload(items: captured) else { return .ignored }
        return .captured(payload)
    }

    static func items(_ payload: ClipboardPayload, marker: Data) -> [NSPasteboardItem] {
        payload.items.map { representations in
            let item = NSPasteboardItem()
            for (type, data) in representations { item.setData(data, forType: NSPasteboard.PasteboardType(type)) }
            item.setData(marker, forType: privateType)
            item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
            item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
            return item
        }
    }

    @discardableResult static func write(_ payload: ClipboardPayload, to board: NSPasteboard, marker: Data = Data(UUID().uuidString.utf8)) -> Bool {
        let prepared = items(payload, marker: marker)
        board.prepareForNewContents(with: .currentHostOnly)
        return board.writeObjects(prepared)
    }
}

final class ClipboardStore: ObservableObject {
    static let shared = ClipboardStore()
    @Published private(set) var entries: [ClipboardEntry] = []
    @Published private(set) var enabled: Bool
    @Published private(set) var paused = false
    @Published private(set) var retention: ClipboardRetention
    @Published private(set) var status: String?

    private var history = ClipboardHistory()
    private let pasteboard: NSPasteboard
    private let defaults: UserDefaults
    private let date: () -> Date
    private let uptime: () -> TimeInterval
    private let reader = DispatchQueue(label: "com.dropshelf.clipboard.read", qos: .utility)
    private var timer: Timer?
    private var observers: [NSObjectProtocol] = []
    private var lockObservers: [NSObjectProtocol] = []
    private var lastChangeCount: Int
    private var captureEpoch = 0
    private var reading = false
    private var suspended = false
    private var screenLocked = false
    private var ownedCopy: (id: UUID, version: Int, marker: Data, wallExpiry: Date, uptimeExpiry: TimeInterval)?

    init(pasteboard: NSPasteboard = .general, defaults: UserDefaults = .standard,
         date: @escaping () -> Date = Date.init,
         uptime: @escaping () -> TimeInterval = { ProcessInfo.processInfo.systemUptime }) {
        self.pasteboard = pasteboard
        self.defaults = defaults
        self.date = date
        self.uptime = uptime
        self.enabled = defaults.bool(forKey: "clipboardHistoryEnabled")
        self.retention = ClipboardRetention(rawValue: defaults.integer(forKey: "clipboardExpirySeconds")) ?? .oneHour
        self.lastChangeCount = pasteboard.changeCount
        history.retention = retention
    }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in self?.poll() }
        timer.tolerance = 0.1
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
        let center = NSWorkspace.shared.notificationCenter
        for name in [NSWorkspace.willSleepNotification, NSWorkspace.screensDidSleepNotification, NSWorkspace.sessionDidResignActiveNotification] {
            observers.append(center.addObserver(forName: name, object: nil, queue: .main) { [weak self] _ in self?.suspend() })
        }
        for name in [NSWorkspace.didWakeNotification, NSWorkspace.screensDidWakeNotification, NSWorkspace.sessionDidBecomeActiveNotification] {
            observers.append(center.addObserver(forName: name, object: nil, queue: .main) { [weak self] _ in self?.resumeSession() })
        }
        let distributed = DistributedNotificationCenter.default()
        lockObservers.append(distributed.addObserver(forName: NSNotification.Name("com.apple.screenIsLocked"), object: nil, queue: .main) { [weak self] _ in self?.lockScreen() })
        lockObservers.append(distributed.addObserver(forName: NSNotification.Name("com.apple.screenIsUnlocked"), object: nil, queue: .main) { [weak self] _ in self?.unlockScreen() })
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        for observer in observers { NSWorkspace.shared.notificationCenter.removeObserver(observer) }
        observers.removeAll()
        for observer in lockObservers { DistributedNotificationCenter.default().removeObserver(observer) }
        lockObservers.removeAll()
        clear()
    }

    func setEnabled(_ value: Bool) {
        guard enabled != value else { return }
        captureEpoch += 1
        enabled = value
        paused = false
        defaults.set(value, forKey: "clipboardHistoryEnabled")
        clear()
        lastChangeCount = pasteboard.changeCount
    }

    func setPaused(_ value: Bool) {
        captureEpoch += 1
        paused = value
        lastChangeCount = pasteboard.changeCount
        prune()
    }

    func setRetention(_ value: ClipboardRetention) {
        retention = value
        history.retention = value
        defaults.set(value.rawValue, forKey: "clipboardExpirySeconds")
        prune()
    }

    func suspend() {
        suspended = true
        clear()
        lastChangeCount = pasteboard.changeCount
    }

    func lockScreen() { screenLocked = true; suspend() }
    func unlockScreen() { screenLocked = false; resumeSession() }

    func resumeSession() {
        guard !screenLocked else { return }
        captureEpoch += 1
        suspended = false
        lastChangeCount = pasteboard.changeCount
        prune()
    }

    func poll() {
        prune()
        guard enabled, !paused, !suspended, !reading else { return }
        let version = pasteboard.changeCount
        guard version != lastChangeCount else { return }
        lastChangeCount = version
        let epoch = captureEpoch
        let name = pasteboard.name
        reading = true
        reader.async { [weak self] in
            let board = NSPasteboard(name: name)
            let result: ClipboardPasteboard.ReadResult = board.changeCount == version ? ClipboardPasteboard.read(board) : .unstable
            DispatchQueue.main.async { [weak self] in
                guard let self = self else { return }
                self.reading = false
                guard epoch == self.captureEpoch, self.enabled, !self.paused, !self.suspended,
                      self.pasteboard.changeCount == version else { return }
                self.accept(result)
            }
        }
    }

    private func accept(_ result: ClipboardPasteboard.ReadResult) {
        switch result {
        case .captured(let payload):
            switch history.capture(payload, at: date(), uptime: uptime()) {
            case .stored: status = nil
            case .tooLarge: status = "Copy not saved: exceeds the memory limit. Original clipboard is unchanged."
            case .full: status = "History is full of pinned entries. Unpin or remove an entry to save new copies."
            }
            publish()
        case .tooLarge: status = "Copy not saved: exceeds 32 MB. Original clipboard is unchanged."
        case .ignored, .unstable: break
        }
    }

    func prune() {
        let oldIDs = history.entries.map(\.id)
        history.prune(at: date(), uptime: uptime())
        if oldIDs != history.entries.map(\.id) { publish() }
        if let owned = ownedCopy {
            if pasteboard.changeCount != owned.version { ownedCopy = nil }
            else if date() >= owned.wallExpiry || uptime() >= owned.uptimeExpiry || !history.entries.contains(where: { $0.id == owned.id }) {
                clearOwnedCopy()
            }
        }
    }

    func payload(for id: UUID) -> ClipboardPayload? {
        prune()
        guard enabled, !suspended else { return nil }
        return history.entries.first { $0.id == id }?.payload
    }

    @discardableResult func copy(_ id: UUID) -> Bool {
        prune()
        guard enabled, !suspended, let entry = history.entries.first(where: { $0.id == id }) else { return false }
        let marker = Data(UUID().uuidString.utf8)
        guard ClipboardPasteboard.write(entry.payload, to: pasteboard, marker: marker) else {
            status = "Could not copy this entry. Try again."
            return false
        }
        lastChangeCount = pasteboard.changeCount
        captureEpoch += 1
        ownedCopy = (entry.id, lastChangeCount, marker, entry.capturedAt.addingTimeInterval(entry.lifetime), entry.capturedUptime + entry.lifetime)
        status = "Copied exactly. Paste with ⌘V."
        return true
    }

    func togglePin(_ id: UUID) { prune(); history.togglePin(id); publish() }
    func remove(_ id: UUID) { history.remove(id); publish(); prune() }
    func clear() {
        captureEpoch += 1
        clearOwnedCopy()
        history.clear()
        publish()
        status = nil
        lastChangeCount = pasteboard.changeCount
    }

    private func clearOwnedCopy() {
        guard let owned = ownedCopy else { return }
        if pasteboard.changeCount == owned.version && pasteboard.data(forType: ClipboardPasteboard.privateType) == owned.marker && pasteboard.changeCount == owned.version {
            pasteboard.prepareForNewContents(with: .currentHostOnly)
        }
        ownedCopy = nil
    }

    private func publish() { entries = history.entries }
}
